config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :experiences
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :traveller, class_name: 'User'
  belongs_to :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :bookings
  has_many :users, through: :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :experiences, foreign_key: :host_id


  validates :email, uniqueness: true
  validates :role, presence: true

  enum role: { traveller: 0, host: 1 }

  before_create :set_default_role

  private
  def set_default_role
    self.role ||= :traveller
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
    else
      render 'new'
    end
  end

  def new
    @booking = Booking.new
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]

  # GET /experiences or /experiences.json
  def index
    @experiences = Experience.all

  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end


  class ExperiencesController < ApplicationController
    def create
      @experience = current_user.experiences.new(experience_params)

      if @experience.save
        redirect_to experiences_path, notice: 'Experience was successfully created.'
      else
        render :new
      end
    end

    private

    def experience_params
      params.require(:experience).permit(:title, :description, :travel_experience, :education)
    end
  end



  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience) do |form| %>
  <% if experience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Show this experience", @experience %> |
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/index.html.erb
<h1>Experiences</h1>

<% @experiences.each do |experience| %>
  <div>
    <h2><%= experience.title %></h2>
    <p><%= experience.description %></p>
    <p><%= link_to "Edit", edit_experience_path(experience) %></p>
  </div>

<% end %>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/show.html.erb
<h1><%= @experience.title %></h1>
<p><%= @experience.description %></p>

<div>
  <%= link_to "Edit this experience", edit_experience_path(@experience) %> |
  <%= link_to "Back to experiences", experiences_path %>

  <%= button_to "Destroy this experience", @experience, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2 class="text-center">About Finca Tierra</h2>
      <p>Finca Tierra is a platform for booking stays at a beautiful farm in the mountains of Costa Rica. We offer a variety of accommodations, from camping to luxury cabins, and a range of activities to make your stay unforgettable. Our farm is located in the mountains of Costa Rica, near the town of San Isidro de El General. We are surrounded by lush tropical rainforest, with stunning views of the Pacific Ocean and the Talamanca mountain range. Our farm is home to a variety of animals, including horses, cows, pigs, chickens, and dogs. We grow a variety of fruits and vegetables on the farm, including bananas, plantains, pineapples, papayas, and more. We also offer a range of activities for our guests to enjoy, including horseback riding, hiking, birdwatching, and more. Whether you're looking for a relaxing getaway or an adventure-filled vacation, Finca Tierra has something for everyone.</p>
    </div>
    <div class="col-md-6">
      <h2 class="text-center">Our Accommodations</h2>
      <p>We offer a variety of accommodations to suit every budget and preference. Our camping area is perfect for those who want to experience the great outdoors, with stunning views of the surrounding mountains and ocean. Our luxury cabins are perfect for those who want a more comfortable and private experience, with all the amenities of home. Our dormitory-style rooms are perfect for groups or solo travelers who want to meet new people and share their experiences. Whatever your preference, we have the perfect accommodation for you at Finca Tierra.</p>
    </div>
  </div>


  <%= link_to "Show all experiences", experiences_path %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar w/ text</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <span class="navbar-text">
        Navbar text with an inline element
      </span>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>